version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"   # JNLP agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # даёт доступ к хостовому docker (см. замечание о безопасности)
      - /usr/bin/docker:/usr/bin/docker             # иногда нужно, чтобы docker-cli был доступен в контейнере
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
volumes:
  jenkins_home:
